# Generated by Django 4.1.1 on 2022-09-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0003_completedwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuraldivisions',
            options={'verbose_name_plural': 'Structural Division'},
        ),
    ]
