# Generated by Django 4.1.1 on 2022-09-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0006_alter_structuraldivisions_curator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuraldivisions',
            name='management_unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReportingTool.structuraldivisions'),
        ),
    ]
