# Generated by Django 4.1.1 on 2022-09-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0009_alter_profession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedwork',
            name='work_notes',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Comments'),
        ),
    ]
