# Generated by Django 4.1.1 on 2022-09-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0010_completedwork_work_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstype',
            name='available_to',
            field=models.ManyToManyField(to='ReportingTool.structuraldivisions'),
        ),
    ]
