# Generated by Django 4.1.1 on 2022-09-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0013_alter_workstype_measure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuraldivisions',
            options={'ordering': ('name',), 'verbose_name_plural': 'Structural Division'},
        ),
        migrations.AlterModelOptions(
            name='workstype',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='structuraldivisions',
            old_name='management_unit_id',
            new_name='management_unit',
        ),
    ]
