# Generated by Django 4.1.1 on 2022-09-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0014_alter_structuraldivisions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='professioncategory',
            options={'verbose_name_plural': 'Profession categories'},
        ),
        migrations.AlterModelOptions(
            name='structuraldivisions',
            options={'ordering': ('name',), 'verbose_name_plural': 'Structural division'},
        ),
    ]
