# Generated by Django 4.1.1 on 2022-09-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReportingTool', '0022_alter_workstype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuraldivisions',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_of_SD', to=settings.AUTH_USER_MODEL),
        ),
    ]
