# Generated by Django 4.1.1 on 2022-09-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0023_alter_structuraldivisions_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='work_notes',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Comments'),
        ),
    ]
