# Generated by Django 4.1.1 on 2022-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0024_alter_completedwork_work_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='work_notes',
            field=models.TextField(blank=True, max_length=70, null=True, verbose_name='Comments'),
        ),
    ]
