# Generated by Django 4.1.1 on 2022-10-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0026_alter_completedwork_work_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedwork',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
