# Generated by Django 4.1.1 on 2022-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReportingTool', '0027_completedwork_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
