# Generated by Django 4.1.1 on 2022-10-22 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReportingTool', '0028_alter_completedwork_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='period',
            field=models.ForeignKey(on_delete=models.SET('deleted date'), to='ReportingTool.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='completedwork',
            name='work_done',
            field=models.ForeignKey(on_delete=models.SET('deleted works type'), to='ReportingTool.workstype', verbose_name='Work done'),
        ),
        migrations.AlterField(
            model_name='completedwork',
            name='work_scope',
            field=models.FloatField(blank=True, null=True, verbose_name='Work scope'),
        ),
        migrations.AlterField(
            model_name='completedwork',
            name='worker',
            field=models.ForeignKey(default='users.CustomUser', on_delete=models.SET('deleted worker'), related_name='worker_do', to=settings.AUTH_USER_MODEL, verbose_name='Worker'),
        ),
        migrations.AlterField(
            model_name='workstype',
            name='name',
            field=models.CharField(max_length=120, verbose_name="Work's name"),
        ),
    ]
